# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserProfile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserProfile
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'Kingfisher'
  pod 'RxKeyboard'

  target 'UserProfileTests' do
    inherit! :search_paths
    # Pods for testing
    
    pod 'RxBlocking'
    pod 'RxTest'

  end

  target 'UserProfileUITests' do
    # Pods for testing
  end

end
